name: Docker Image CI - HTML

on:
  push:
    branches: [ "main" ]
    path:
      - 'html/**' 
  pull_request:
    branches: [ "main" ]
    path:
      - 'html/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd html
        docker build . --file Dockerfile --tag ghcr.io/dominate2/html-13a:0.1
        docker login ghcr.io -u dominate2 -p ${{secrets.GHCR_TOKEN}}
        docker push ghcr.io/dominate2/html-13a:0.1
